//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoHighCharts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirectOrder()
        {
            this.DirectOrderDetails = new HashSet<DirectOrderDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ArrivedTime { get; set; }
        public Nullable<System.DateTime> LeavedTime { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirectOrderDetail> DirectOrderDetails { get; set; }
        public virtual Table Table { get; set; }
    }
}
