//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoHighCharts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectOrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> DirectOrderId { get; set; }
        public Nullable<int> MenuItemId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> PriceEach { get; set; }
    
        public virtual DirectOrder DirectOrder { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
